package com.project.oop.tasksmanagement.commands.enums;

public enum CommandType {
    ADDBOARD,
    ADDCOMMENT,
    REMOVECOMMENT,
    ADDMEMBERTOTEAM,
    CREATEMEMBER,
    CREATETEAM,
    ADDTASK,
    CHANGETASK,
    ASSIGNTASK,
    UNASSIGNTASK,
    SHOWALL,
    SHOWACTIVITY,
    LISTALL,
    LISTASSIGNEDTASKS,
    SHOWTEAMDEVELOPERS,
    SHOWTEAMBOARDS
}
