package com.project.oop.tasksmanagement.commands.enums;

public enum CommandType {
    ADDBOARD,
    ADDTASK,
    ADDMEMBERTOTEAM,
    ADDBUGREPRODUCESTEPS,
    ASSIGNTASK,
    UNASSIGNTASK,
    ADDCOMMENT,
    REMOVECOMMENT,
    CREATEMEMBER,
    CREATETEAM,
    CHANGETASK,
    SHOWALL,
    SHOWACTIVITY,
    SHOWTEAMMEMBERS,
    SHOWTEAMBOARDS,
    LISTALLTASKS,
    LISTALLBUGS,
    LISTASSIGNEDTASKS,
    LISTALLSTORIES,
    HELP


}
